// faculty
export const FACULTY_LOADING = "FACULTY_LOADING";
export const FETCH_FACULT = "FETCH_FACULT";
export const FACULTY_ERROR = "FACULTY_ERROR";
export const CREATE_FACULTY = "CREATE_FACULTY";
export const CREATE_FACULTY_LOADING = "CREATE_FACULTY_LOADING";
export const DELETE_FACULTY = "DELETE_FACULTY";
export const SET_EDIT_FACULTY = "SET_EDIT_FACULTY";
export const SET_FACULTY_ID = "SET_FACULTY_ID";
export const UPDATE_FACULTY = "UPDATE_FACULTY";